version: '3'

services:
  web:
    image: nginx:1.21-alpine
    container_name: nginx
    ports:
      - "80:80"
    working_dir: /workspace
    # networks:
    #   default:
    #     aliases:
    #       - app
    depends_on:
      - app
    volumes:
      - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf
      - ~/.ssh:/root/.ssh #sshキー
      - ~/.gitconfig:/root/.gitconfig #gitの設定
      - ../:/workspace:cached
  
  app:
    build:
      context: ./docker/app
    container_name: app
    # working_dir: /workspace
    command: sleep infinity
    ports:
      - "4000:4000"
      - "3000:3000"
    volumes:
      - ../:/workspace:cached
      # - workspace:/workspace
      # - node-modules:/workspace/node_modules
      

volumes:
  workspace: null
  node-modules: null